name: update readme
permissions:
  contents: write
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
    update-readme-with-blog:
      name: Update this repo's README with latest blog posts
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Pull in dev.to posts
          uses: gautamkrishnar/blog-post-workflow@master
          with:
            feed_list: "https://dev.to/feed/jecrs687"
            
    devcard:
      name: Update dev card posts
      runs-on: ubuntu-latest
      steps:
        - name: devcard
          uses: dailydotdev/action-devcard@2.0.2
          with:
            devcard_id: ${{ secrets.DEVCARD_ID }}
            
    update-readme:
      name: Update wakatime with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            
    update-snake:
      name: Update snake stars 
      runs-on: ubuntu-latest
      steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
